-- 1. Create Dreams Summary Questions (for the Manual UI Tab)
CREATE TABLE IF NOT EXISTS dreams_summary_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_number INTEGER NOT NULL,
    section_header TEXT,
    question_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

TRUNCATE dreams_summary_questions;
INSERT INTO dreams_summary_questions (sequence_number, section_header, question_text) VALUES
(1, 'Dream', 'Which quality/ value/ ability that you already have will help you achieve your dream?'),
(2, NULL, 'What do you need to do to make sure this dream does not fail?'),
(3, NULL, 'To achieve this dream, what do you need to study after Class 10? (if applicable)');

-- Dreams Translations
INSERT INTO content_translations (resource_type, resource_key, lang, text) VALUES
('dreams_summary_question', 'header1', 'ta', 'கனவு'),
('dreams_summary_question', 'question1', 'ta', 'உங்களிடம் ஏற்கனவே உள்ள எந்த குணம் / மதிப்பு / திறன் இந்த கனவை அடைய உங்களுக்கு உதவும்?'),
('dreams_summary_question', 'question2', 'ta', 'இந்த கனவு தோல்வியடையாமல் இருக்க நீங்கள் என்ன செய்ய வேண்டும்?'),
('dreams_summary_question', 'question3', 'ta', 'இந்த கனவை அடைய 10ஆம் வகுப்பிற்குப் பிறகு நீங்கள் என்ன படிக்க வேண்டும்? (தேவையானால்)'),
('dreams_summary_question', 'header1', 'kn', 'ಕನಸು'),
('dreams_summary_question', 'question1', 'kn', 'ನಿಮ್ಮಲ್ಲಿ ಈಗಾಗಲೇ ಕಂಡುಕೊಂಡಿರುವ ಯಾವ ಗುಣ/ ಮೌಲ್ಯ/ ಸಾರ್ಥ್ಯ ನಿಮ್ಮ ಕನಸನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.'),
('dreams_summary_question', 'question2', 'kn', 'ಕನಸು ವಿಫಲವಾಗುವುದಿಲ್ಲ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನೀವು ಏನು ಮಾಡಬೇಕಾಗುತ್ತದೆ'),
('dreams_summary_question', 'question3', 'kn', 'ಈ ಕನಸನ್ನುಸಾಧಿಸಲು ೧೦ನೇ ತರಗತಿಯ ನಂತರ ನೀವು ಏನು ಅಧ್ಯಯನ ಮಾಡಬೇಕು? (ಅನ್ವಯಿಸಿದರೆ)')
ON CONFLICT (resource_type, resource_key, lang) DO UPDATE SET text = EXCLUDED.text;

-- 2. AI Template Update for My Dreams
INSERT INTO assessment_summary_templates (assessment_type, title, summary_questions) VALUES
('dreams', 'Summary: My Dreams', 
 '{
   "en": {
     "title": "Dream",
     "question1": "Which quality/ value/ ability that you already have will help you achieve your dream?",
     "question2": "What do you need to do to make sure this dream does not fail?",
     "question3": "To achieve this dream, what do you need to study after Class 10? (if applicable)"
   },
   "ta": {
     "title": "கனவு",
     "question1": "உங்களிடம் ஏற்கனவே உள்ள எந்த குணம் / மதிப்பு / திறன் இந்த கனவை அடைய உங்களுக்கு உதவும்?",
     "question2": "இந்த கனவு தோல்வியடையாமல் இருக்க நீங்கள் என்ன செய்ய வேண்டும்?",
     "question3": "இந்த கனவை அடைய 10ஆம் வகுப்பிற்குப் பிறகு நீங்கள் என்ன படிக்க வேண்டும்? (தேவையானால்)"
   },
   "kn": {
     "title": "ಕನಸು",
     "question1": "ನಿಮ್ಮಲ್ಲಿ ಈಗಾಗಲೇ ಕಂಡುಕೊಂಡಿರುವ ಯಾವ ಗುಣ/ ಮೌಲ್ಯ/ ಸಾರ್ಥ್ಯ ನಿಮ್ಮ ಕನಸನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
     "question2": "ಕನಸು ವಿಫಲವಾಗುವುದಿಲ್ಲ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನೀವು ಏನು ಮಾಡಬೇಕಾಗುತ್ತದೆ",
     "question3": "ಈ ಕನಸನ್ನುಸಾಧಿಸಲು ೧೦ನೇ ತರಗತಿಯ ನಂತರ ನೀವು ಏನು ಅಧ್ಯಯನ ಮಾಡಬೇಕು? (ಅನ್ವಯಿಸಿದರೆ)"
   }
 }'::jsonb)
ON CONFLICT (assessment_type) DO UPDATE SET title = EXCLUDED.title, summary_questions = EXCLUDED.summary_questions, updated_at = NOW();

-- 3. Stored procedure to fetch manual summary questions for Dreams
CREATE OR REPLACE FUNCTION get_dreams_summary_questions_i18n(p_lang TEXT)
RETURNS TABLE (
    id BIGINT,
    sequence_number INTEGER,
    section_header TEXT,
    question_text TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        q.id,
        q.sequence_number,
        COALESCE(ct_h.text, q.section_header) as section_header,
        COALESCE(ct_q.text, q.question_text) as question_text
    FROM dreams_summary_questions q
    LEFT JOIN content_translations ct_h 
        ON ct_h.resource_type = 'dreams_summary_question' 
        AND ct_h.resource_key = 'header' || q.sequence_number::text 
        AND ct_h.lang = p_lang
    LEFT JOIN content_translations ct_q 
        ON ct_q.resource_type = 'dreams_summary_question' 
        AND ct_q.resource_key = 'question' || q.sequence_number::text 
        AND ct_q.lang = p_lang
    ORDER BY q.sequence_number;
END;
$$ LANGUAGE plpgsql;
