export type StudentLang = 'en' | 'kn' | 'ta' | 'hi';

const strings: Record<StudentLang, Record<string, string>> = {
    en: {
        brand: 'Career Compass',
        menu_profile: 'My Profile',
        menu_messages: 'Messages',
        menu_logout: 'Logout',
        welcome_title: 'Welcome to Your Career Journey',
        welcome_body:
            "Welcome, young explorer, to the thrilling Career Discovery Journey! We invite you to step into this interactive space with curiosity and embark on a curated journey of Self-Discovery and comprehensive career exposure, designed to pave your path toward a productive future. Through engaging and carefully developed modules, you will explore your core interests, unlock your unique abilities, and define your personal dreams and aspirations. This journey is personalized, allowing ample time for reflection and exploration. Our specialized Vidya Saathis are integral to this process; they actively review your input, helping you chart your course, offering expert assessment, mentorship, and personalized guidance every step of the way to ensure you make informed decisions about your educational and career choices.",
        progress_title: 'Your Journey Progress',
        assessments_total: 'Assessments Total',
        complete_suffix: 'Complete',
        completed: 'Completed ✓',
        in_progress: 'In Progress',
        not_started: 'Not Started',
        available: 'Available',
        locked: 'Locked 🔒',
        start_here: 'Start Here',
        progress_summary_title: 'Assessment Progress Summary',
        progress_summary_desc: 'Track your completion status across all assessments',
        tests_title: 'Psychometric Tests',
        tests_item: 'Psychometric Tests – Holland Code Assessment',
        tests_open: 'Open 🔓',
        chat_title: 'CareerChat LM',
        chat_desc: 'Get personalized career guidance based on your assessment responses',
        chat_placeholder: 'Ask me about your career path...',
        chat_send_hint: 'AI-powered career guidance',
        chat_greeting: "Hello! I'm here to help guide your career journey. Based on your assessments, I can provide personalized advice and suggestions.",
        assessment_inspiration: 'My Inspiration',
        assessment_about_me: 'About Me',
        assessment_dreams: 'My Dreams',
        assessment_school_learning: 'My School, My Learning and I',
        assessment_hobbies: 'My Talents and Hobbies',
        assessment_role_models: 'My Role Models',
        assessment_holland_code: 'Holland Code (RIASEC) Test',
        assessment_career_guidance: 'Exploring Career Guidance Tools',
        my_profile_card: 'My Profile Card',
        things_interest_me: 'Things that Interest Me',
        career_roadmap: 'Career Roadmap',
        view_summary: 'View Summary',
        view_responses: 'View Summary',
        summary_pending: 'Summary Pending Review',
        summary_pending_short: 'Summary Pending...',
        compass_subtitle: 'Your personal career profile, built from your journey',
        complete_module_nudge: 'Complete this module to see your personal insights',
        career_direction_motivational: 'Complete all 6 modules and your unique career direction will appear here',
        generating_keywords: 'Generating keywords...',
        generating_direction: 'Generating your career direction...',
        roadmap_enter_career: 'Enter career option...',
        roadmap_available_later: 'Available later',
        roadmap_all_saved: 'All changes saved',
        roadmap_saving: 'Saving...',
        roadmap_save_failed: 'Save failed',
    },
    kn: {
        brand: 'Career Compass',
        menu_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
        menu_settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
        menu_logout: 'ಲಾಗ್ ಔಟ್',
        welcome_title: 'ನಿಮ್ಮ ವೃತ್ತಿ ಪ್ರಯಾಣಕ್ಕೆ ಸ್ವಾಗತ',
        welcome_body:
            'ಸ್ವಾಗತ, ಕಿರಿಯ ಅನ್ವೇಷಕನೇ! ಇದು ನಿಮ್ಮ ಆಕರ್ಷಕ ವೃತ್ತಿ ಅನ್ವೇಷಣೆಯ ಪ್ರಯಾಣ. ಕುತೂಹಲದಿಂದ ಈ ಅಂತರ್ಕ್ರಿಯಾತ್ಮಕ ಜಾಗಕ್ಕೆ ಪ್ರವೇಶಿಸಿ, ಸ್ವ-ಅನ್ವೇಷಣೆ ಮತ್ತು ವೃತ್ತಿ ಪರಿಚಯದ ಸಂಯೋಜಿತ ಪ್ರಯಾಣವನ್ನು ಆರಂಭಿಸಿ. ಇಲ್ಲಿ ನೀವು ನಿಮ್ಮ ಆಸಕ್ತಿಗಳನ್ನು, ಸಾಮರ್ಥ್ಯಗಳನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ ಮತ್ತು ನಿಮ್ಮ ಕನಸುಗಳನ್ನು ರೂಪಿಸಿ. ನಮ್ಮ ವಿಶೇಷ ವಿದ್ಯಾ ಸಾಥಿಗಳು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತಾರೆ, ನಿಮ್ಮ ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ ಆಯ್ಕೆಗಳ ಬಗ್ಗೆ ತಿಳಿದ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತಾರೆ.',
        progress_title: 'ನಿಮ್ಮ ಪ್ರಯಾಣದ ಪ್ರಗತಿ',
        assessments_total: 'ಮೌಲ್ಯಮಾಪನಗಳ ಒಟ್ಟು',
        complete_suffix: 'ಪೂರ್ಣ',
        completed: 'ಪೂರ್ಣಗೊಂಡ ✓',
        in_progress: 'ನಡೆಯುತ್ತಿದೆ',
        not_started: 'ಆರಂಭವಾಗಿಲ್ಲ',
        available: 'ಲಭ್ಯ',
        locked: 'ಲಾಕ್ 🔒',
        start_here: 'ಇಲ್ಲಿಂದ ಪ್ರಾರಂಭಿಸಿ',
        progress_summary_title: 'ಮೌಲ್ಯಮಾಪನ ಪ್ರಗತಿ ಸಾರಾಂಶ',
        progress_summary_desc: 'ಎಲ್ಲಾ ಮೌಲ್ಯಮಾಪನಗಳ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
        tests_title: 'ಮಾನಸಿಕ ಪರೀಕ್ಷೆಗಳು',
        tests_item: 'ಮಾನಸಿಕ ಪರೀಕ್ಷೆಗಳು – ಹಾಲೆಂಡ್ ಕೋಡ್ ಅಸೆಸ್ಮೆಂಟ್',
        tests_open: 'ತೆರೆಯಿರಿ 🔓',
        chat_title: 'ಕೆರಿಯರ್ ಚಾಟ್',
        chat_desc: 'ನಿಮ್ಮ ಮೌಲ್ಯಮಾಪನಗಳ ಆಧಾರದ ಮೇಲೆ ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನ',
        chat_placeholder: 'ನಿಮ್ಮ ವೃತ್ತಿ ಬಗ್ಗೆ ನನ್ನನ್ನು ಕೇಳಿ...',
        chat_send_hint: 'AI ಆಧಾರಿತ ವೃತ್ತಿ ಮಾರ್ಗದರ್ಶನ',
        chat_greeting: 'ನಮಸ್ಕಾರ! ನಿಮ್ಮ ವೃತ್ತಿ ಪ್ರಯಾಣದಲ್ಲಿ ಮಾರ್ಗದರ್ಶನ ನೀಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ. ನಿಮ್ಮ ಮೌಲ್ಯಮಾಪನಗಳ ಆಧಾರದ ಮೇಲೆ, ನಾನು ವೈಯಕ್ತಿಕ ಸಲಹೆ ಮತ್ತು ಸೂಚನೆಗಳನ್ನು ನೀಡಬಹುದು.',
        assessment_inspiration: 'ನನ್ನ ಪ್ರೇರಣೆ',
        assessment_about_me: 'ನನ್ನ ಬಗ್ಗೆ',
        assessment_dreams: 'ನನ್ನ ಕನಸುಗಳು',
        assessment_school_learning: 'ನನ್ನ ಶಾಲೆ, ನನ್ನ ಕಲಿಕೆ',
        assessment_hobbies: 'ನನ್ನ ಪ್ರತಿಭೆಗಳು ಮತ್ತು ಹವ್ಯಾಸಗಳು',
        assessment_role_models: 'ನನ್ನ ಆದರ್ಶ ವ್ಯಕ್ತಿ ಯಾರು?',
        assessment_holland_code: 'ಹಾಲೆಂಡ್ ಕೋಡ್ (RIASEC) ಪರೀಕ್ಷೆ',
        assessment_career_guidance: 'ವೃತ್ತಿ ಮಾರ್ಗದರ್ಶನ ಸಾಧನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
        my_profile_card: 'ನನ್ನ ಪ್ರೊಫೈಲ್ ಕಾರ್ಡ್',
        things_interest_me: 'ನನಗೆ ಆಸಕ್ತಿ ಇರುವ ವಿಷಯಗಳು',
        career_roadmap: 'ವೃತ್ತಿ ರೋಡ್‌ಮ್ಯಾಪ್',
        view_summary: 'ಸಾರಾಂಶ ವೀಕ್ಷಿಸಿ',
        view_responses: 'ಸಾರಾಂಶ ನೋಡಿ',
        summary_pending: 'ಸಾರಾಂಶ ವಿಮರ್ಶೆ ಬಾಕಿ',
        summary_pending_short: 'ಸಾರಾಂಶ ಬಾಕಿ...',
        menu_messages: 'ಸಂದೇಶಗಳು',
        compass_subtitle: 'ನಿಮ್ಮ ಪ್ರಯಾಣದಿಂದ ನಿರ್ಮಿಸಲಾದ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವೃತ್ತಿ ಪ್ರೊಫೈಲ್',
        complete_module_nudge: 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಒಳನೋಟಗಳನ್ನು ನೋಡಲು ಈ ಮಾಡ್ಯೂಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
        career_direction_motivational: 'ಎಲ್ಲಾ 6 ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ನಿಮ್ಮ ವಿಶಿಷ್ಟ ವೃತ್ತಿ ದಿಕ್ಕು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ',
        generating_keywords: 'ಕೀವರ್ಡ್‌ಗಳನ್ನು ಉತ್ಪಾದಿಸಲಾಗುತ್ತಿದೆ...',
        generating_direction: 'ನಿಮ್ಮ ವೃತ್ತಿ ದಿಕ್ಕನ್ನು ಉತ್ಪಾದಿಸಲಾಗುತ್ತಿದೆ...',
        roadmap_enter_career: 'ವೃತ್ತಿ ಆಯ್ಕೆಯನ್ನು ನಮೂದಿಸಿ...',
        roadmap_available_later: 'ನಂತರ ಲಭ್ಯ',
        roadmap_all_saved: 'ಎಲ್ಲಾ ಬದಲಾವಣೆಗಳು ಉಳಿಸಲಾಗಿದೆ',
        roadmap_saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
        roadmap_save_failed: 'ಉಳಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ',
    },
    ta: {
        brand: 'Career Compass',
        menu_profile: 'என் விவரம்',
        menu_messages: 'செய்திகள்',
        menu_settings: 'அமைப்புகள்',
        menu_logout: 'வெளியேறு',
        welcome_title: 'உங்கள் தொழில் பயணத்திற்கு வரவேற்பு',
        welcome_body:
            'வணக்கம் மாணவா்! இந்த தளத்தில் நீங்கள் எளிய கேள்விகளுக்கு பதில் எழுதலாம். உங்கள் எண்ணங்கள், கனவுகள் மற்றும் திறன்களை மெதுவாக தெரிந்து கொள்ளலாம். இது உங்கள் படிப்பு மற்றும் தொழில் பற்றி யோசிக்க உதவும்.',
        progress_title: 'உங்கள் முன்னேற்றம்',
        assessments_total: 'மொத்த செயல்கள்',
        complete_suffix: 'முடிந்தது',
        completed: 'முடிந்தது ✓',
        in_progress: 'நடந்து கொண்டிருக்கிறது',
        not_started: 'இன்னும் தொடங்கவில்லை',
        available: 'செய்யலாம்',
        locked: 'பூட்டப்பட்டது 🔒',
        start_here: 'இங்கே தொடங்கு',
        progress_summary_title: 'செயல்களின் நிலை',
        progress_summary_desc: 'எந்த செயல்கள் முடிந்தது, எது மீதம் என்று பார்க்கலாம்',
        tests_title: 'மனப்பாங்கு சோதனை',
        tests_item: 'ஹால்லண்ட் கோட் சோதனை',
        tests_open: 'திறக்கவும் 🔓',
        chat_title: 'CareerChat LM',
        chat_desc: 'உங்கள் பதில்களின் அடிப்படையில் எளிய தொழில் வழிகாட்டல்',
        chat_placeholder: 'உங்கள் எதிர்காலம் பற்றி என்னைக் கேளுங்கள்...',
        chat_send_hint: 'AI அடிப்படையிலான தொழில் உதவி',
        chat_greeting: 'வணக்கம்! உங்கள் தொழில் பயணத்தில் உங்களுக்கு வழிகாட்ட நான் இருக்கிறேன். நீங்கள் எழுதிய மதிப்பீடுகளின் அடிப்படையில், உங்களுக்கு தனிப்பட்ட ஆலோசனைகளையும் பரிந்துரைகளையும் வழங்க முடியும்.',
        assessment_inspiration: 'என் உத்வேகம்',
        assessment_about_me: 'என்னைப் பற்றி',
        assessment_dreams: 'என் கனவுகள்',
        assessment_school_learning: 'நானும், என் பள்ளியும், என் கற்றலும்',
        assessment_hobbies: 'என் திறமைகள் மற்றும் பொழுதுபோக்குகள்',
        assessment_role_models: 'என் முன்மாதிரி நபர்',
        assessment_holland_code: 'ஹாலண்ட் குறியீடு (RIASEC) தேர்வு',
        assessment_career_guidance: 'தொழில் வழிகாட்டல் கருவிகளை அறிதல்',
        my_profile_card: 'என் சுயவிவர அட்டை',
        things_interest_me: 'எனக்கு ஆர்வமான விஷயங்கள்',
        career_roadmap: 'தொழில் வழிகாட்டி',
        view_summary: 'சுருக்கம் பார்க்கவும்',
        view_responses: 'சுருக்கத்தைப் பார்க்க',
        summary_pending: 'சுருக்கம் ஆசிரியர் பார்வைக்கு உள்ளது',
        summary_pending_short: 'சுருக்கம் நிலுவையில்...',
        compass_subtitle: 'உங்கள் பயணத்திலிருந்து உருவாக்கப்பட்ட உங்கள் தொழில் சுயவிவரம்',
        complete_module_nudge: 'உங்கள் தனிப்பட்ட நுண்ணறிவுகளைக் காண இந்தப் பிரிவை முடிக்கவும்',
        career_direction_motivational: 'அனைத்து 6 பிரிவுகளையும் முடிக்கவும், உங்கள் தனித்துவமான தொழில் திசை இங்கே தோன்றும்',
        generating_keywords: 'முக்கிய வார்த்தைகள் உருவாக்கப்படுகின்றன...',
        generating_direction: 'உங்கள் தொழில் திசையை உருவாக்குகிறது...',
        roadmap_enter_career: 'தொழில் விருப்பத்தை உள்ளிடவும்...',
        roadmap_available_later: 'பின்னர் கிடைக்கும்',
        roadmap_all_saved: 'அனைத்து மாற்றங்களும் சேமிக்கப்பட்டன',
        roadmap_saving: 'சேமிக்கிறது...',
        roadmap_save_failed: 'சேமிப்பு தோல்வியடைந்தது',
    },
    hi: {
        brand: 'Career Compass',
        menu_profile: 'मेरी प्रोफ़ाइल',
        menu_messages: 'संदेश',
        menu_logout: 'लॉग आउट',
        welcome_title: 'आपकी करियर यात्रा में स्वागत है',
        welcome_body:
            'स्वागत है, युवा खोजकर्ता! यह आपकी रोमांचक करियर खोज यात्रा है। जिज्ञासा के साथ इस इंटरैक्टिव स्थान में कदम रखें और आत्म-खोज तथा व्यापक करियर परिचय की एक संयोजित यात्रा शुरू करें। यहाँ आप अपनी रुचियों, क्षमताओं को जानेंगे और अपने सपनों को आकार देंगे। हमारे विशेष विद्या साथी आपकी प्रतिक्रियाओं की समीक्षा करके मार्गदर्शन देंगे, ताकि आप अपनी शिक्षा और करियर के बारे में सोच-समझकर निर्णय ले सकें।',
        progress_title: 'आपकी यात्रा की प्रगति',
        assessments_total: 'कुल मूल्यांकन',
        complete_suffix: 'पूर्ण',
        completed: 'पूर्ण ✓',
        in_progress: 'प्रगति में',
        not_started: 'शुरू नहीं हुआ',
        available: 'उपलब्ध',
        locked: 'लॉक 🔒',
        start_here: 'यहाँ से शुरू करें',
        progress_summary_title: 'मूल्यांकन प्रगति सारांश',
        progress_summary_desc: 'सभी मूल्यांकनों की प्रगति को ट्रैक करें',
        tests_title: 'मनोवैज्ञानिक परीक्षण',
        tests_item: 'मनोवैज्ञानिक परीक्षण – हॉलैंड कोड मूल्यांकन',
        tests_open: 'खोलें 🔓',
        chat_title: 'करियर चैट',
        chat_desc: 'आपके मूल्यांकन उत्तरों के आधार पर व्यक्तिगत करियर मार्गदर्शन',
        chat_placeholder: 'अपने करियर के बारे में पूछें...',
        chat_send_hint: 'AI आधारित करियर मार्गदर्शन',
        chat_greeting: 'नमस्ते! आपकी करियर यात्रा में मार्गदर्शन करने के लिए मैं यहाँ हूँ। आपके मूल्यांकनों के आधार पर, मैं व्यक्तिगत सलाह और सुझाव दे सकता हूँ।',
        assessment_inspiration: 'मेरी प्रेरणा',
        assessment_about_me: 'मेरे बारे में',
        assessment_dreams: 'मेरे सपने',
        assessment_school_learning: 'मेरा स्कूल, मेरी पढ़ाई और मैं',
        assessment_hobbies: 'मेरी प्रतिभाएँ और शौक',
        assessment_role_models: 'मेरे आदर्श',
        assessment_holland_code: 'हॉलैंड कोड (RIASEC) परीक्षा',
        assessment_career_guidance: 'करियर मार्गदर्शन उपकरणों की खोज',
        my_profile_card: 'मेरा प्रोफ़ाइल कार्ड',
        things_interest_me: 'मुझे रुचि रखने वाली चीज़ें',
        career_roadmap: 'करियर रोडमैप',
        view_summary: 'सारांश देखें',
        view_responses: 'सारांश देखें',
        summary_pending: 'सारांश समीक्षा के लिए लंबित',
        summary_pending_short: 'सारांश लंबित...',
        compass_subtitle: 'आपकी यात्रा से बना आपका व्यक्तिगत करियर प्रोफ़ाइल',
        complete_module_nudge: 'अपनी व्यक्तिगत जानकारी देखने के लिए यह मॉड्यूल पूरा करें',
        career_direction_motivational: 'सभी 6 मॉड्यूल पूरे करें और आपकी अनूठी करियर दिशा यहाँ दिखाई देगी',
        generating_keywords: 'कीवर्ड तैयार हो रहे हैं...',
        generating_direction: 'आपकी करियर दिशा तैयार हो रही है...',
        roadmap_enter_career: 'करियर विकल्प दर्ज करें...',
        roadmap_available_later: 'बाद में उपलब्ध',
        roadmap_all_saved: 'सभी बदलाव सहेजे गए',
        roadmap_saving: 'सहेजा जा रहा है...',
        roadmap_save_failed: 'सहेजना विफल',
    },
};

export function useStudentStrings(lang: StudentLang) {
    const t = (key: string): string => (strings[lang] && strings[lang][key]) || strings.en[key] || key;
    return { t, strings };
}
