import { logger } from '@/lib/logger';

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

logger.log('Supabase client configuration:', {
  url: SUPABASE_URL,
  key: SUPABASE_PUBLISHABLE_KEY ? 'Key present' : 'Key missing',
  databaseTypes: typeof Database
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

logger.log('Supabase client created successfully');

// Test basic connection
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    logger.error('Supabase connection test failed:', error);
  } else {
    logger.log('Supabase connection test successful');
  }
});