export type TeacherLang = 'en' | 'kn' | 'ta' | 'hi';

const strings: Record<TeacherLang, Record<string, any>> = {
    en: {
        brand: 'Vidya Saathi',
        welcome: (name: string) => `Welcome, ${name}!`,
        manageStudents: 'Manage your students and guide them through their career journey',
        totalStudents: 'Total Students',
        activeStudents: 'Active Students',
        recentAdditions: 'Recent Additions',
        studentsTab: 'Students',
        reviewsTab: 'Reviews',
        resourcesTab: 'Resources',
        analyticsTab: 'Analytics',
        addStudent: 'Add Student',
        addExisting: 'Add Existing Student',
        importCsv: 'Import CSV',
        studentManagement: 'Student Management',
        studentListEmpty: 'No students found',
        tryAdjustFilters: 'Try adjusting your search or filters',
        getStartedAdding: 'Get started by adding your first student',
        startFirstStudent: 'Add Your First Student',
        temporaryPassword: 'Temporary password for new student accounts:',
        reviewedLabel: 'reviewed',
        logout: 'Logout',
        myProfile: 'My Profile',
        contactIlp: 'Contact ILP',
        inspirationTitle: 'MY INSPIRATION',
        aboutMeTitle: 'ABOUT ME',
    },
    kn: {
        brand: 'ವಿದ್ಯಾ ಸಾಥಿ',
        welcome: (name: string) => `ಸ್ವಾಗತ, ${name}!`,
        manageStudents: 'ನಿಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಅವರ ವೃತ್ತಿ ಪ್ರಯಾಣಕ್ಕೆ ಮಾರ್ಗದರ್ಶನ ನೀಡಿ',
        totalStudents: 'ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು',
        activeStudents: 'ಸಕ್ರಿಯ ವಿದ್ಯಾರ್ಥಿಗಳು',
        recentAdditions: 'ಇತ್ತೀಚಿನ ಸೇರಿಕೆಗಳು',
        studentsTab: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
        reviewsTab: 'ಪರಿಶೀಲನೆಗಳು',
        resourcesTab: 'ಸಂಪನ್ಮೂಲಗಳು',
        analyticsTab: 'ವಿಶ್ಲೇಷಣೆ',
        addStudent: 'ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಸೇರಿಸಿ',
        addExisting: 'ಇದ್ದ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಸೇರಿಸಿ',
        importCsv: 'CSV ಆಮದು',
        studentManagement: 'ವಿದ್ಯಾರ್ಥಿ ನಿರ್ವಹಣೆ',
        studentListEmpty: 'ಯಾವುದೇ ವಿದ್ಯಾರ್ಥಿಗಳು ಕಂಡುಬರಲಿಲ್ಲ',
        tryAdjustFilters: 'ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಪರಿಷ್ಕರಿಸಿ ಪ್ರಯತ್ನಿಸಿ',
        getStartedAdding: 'ಮೊದಲ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಸೇರಿಸುವುದರಿಂದ ಪ್ರಾರಂಭಿಸಿ',
        startFirstStudent: 'ಮೊದಲ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಸೇರಿಸಿ',
        temporaryPassword: 'ಹೊಸ ವಿದ್ಯಾರ್ಥಿಗಳ ತಾತ್ಕಾಲಿಕ ಪಾಸ್ವರ್ಡ್:',
        reviewedLabel: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
        logout: 'ಲಾಗ್ ಔಟ್',
        myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
        contactIlp: 'ILP ಸಂಪರ್ಕಿಸಿ',
        inspirationTitle: 'ನನ್ನ ಪ್ರೇರಣೆ',
        aboutMeTitle: 'ನನ್ನ ಬಗ್ಗೆ',
    },
    ta: {
        brand: 'வித்யா சாதி',
        welcome: (name: string) => `வணக்கம், ${name}!`,
        manageStudents: 'உங்கள் மாணவர்களை பார்த்து அவர்களுக்கு உதவுங்கள்',
        totalStudents: 'மொத்த மாணவர்கள்',
        activeStudents: 'படிக்கும் மாணவர்கள்',
        recentAdditions: 'புதிதாக சேர்க்கப்பட்டவர்கள்',
        studentsTab: 'மாணவர்கள்',
        reviewsTab: 'பார்வைகள்',
        resourcesTab: 'பயனுள்ள விஷயங்கள்',
        analyticsTab: 'விவரங்கள்',
        addStudent: 'மாணவரை சேர்',
        addExisting: 'இருக்கும் மாணவரை சேர்',
        importCsv: 'CSV பட்டியலை சேர்',
        studentManagement: 'மாணவர்களை பார்த்தல்',
        studentListEmpty: 'மாணவர்கள் இல்லை',
        tryAdjustFilters: 'தேடலை மாற்றி முயற்சிக்கவும்',
        getStartedAdding: 'முதல் மாணவரை சேர்த்து தொடங்குங்கள்',
        startFirstStudent: 'முதல் மாணவரை சேர்',
        temporaryPassword: 'புதிய மாணவர் கடவுச்சொல்:',
        reviewedLabel: 'பார்த்துவிட்டது',
        logout: 'வெளியேறு',
        myProfile: 'என் விவரம்',
        contactIlp: 'ILP தொடர்பு',
        inspirationTitle: 'என் உத்வேகம்',
        aboutMeTitle: 'என்னைப் பற்றி',
    },
    hi: {
        brand: 'विद्या साथी',
        welcome: (name: string) => `स्वागत है, ${name}!`,
        manageStudents: 'अपने छात्रों को देखें और उनकी करियर यात्रा में मार्गदर्शन करें',
        totalStudents: 'कुल छात्र',
        activeStudents: 'सक्रिय छात्र',
        recentAdditions: 'हाल में जोड़े गए',
        studentsTab: 'छात्र',
        reviewsTab: 'समीक्षाएं',
        resourcesTab: 'संसाधन',
        analyticsTab: 'विश्लेषण',
        addStudent: 'छात्र जोड़ें',
        addExisting: 'मौजूदा छात्र जोड़ें',
        importCsv: 'CSV आयात करें',
        studentManagement: 'छात्र प्रबंधन',
        studentListEmpty: 'कोई छात्र नहीं मिला',
        tryAdjustFilters: 'खोज या फ़िल्टर बदलकर देखें',
        getStartedAdding: 'पहला छात्र जोड़कर शुरू करें',
        startFirstStudent: 'पहला छात्र जोड़ें',
        temporaryPassword: 'नए छात्र खातों के लिए अस्थायी पासवर्ड:',
        reviewedLabel: 'समीक्षित',
        logout: 'लॉगआउट',
        myProfile: 'मेरी प्रोफ़ाइल',
        contactIlp: 'ILP से संपर्क करें',
        inspirationTitle: 'मेरी प्रेरणा',
        aboutMeTitle: 'मेरे बारे में',
    },
};

export function useTeacherStrings(lang: TeacherLang) {
    const t = (k: string): string => (strings[lang] as any)[k] || (strings.en as any)[k] || k;
    const welcomeMessage = (name: string): string => (strings[lang].welcome as (n: string) => string)(name);
    return { t, welcomeMessage, strings };
}
